[cluster]
rpc_url = "https://api.devnet.solana.com"
program_id = "FRsToriMLgDc1Ud53ngzHUZvCRoazCaGeGUuzkwoha7m"
payer = "/home/clawd/.config/solana/id.json"

[vm]
seed = 13770557880015489434
account_model = "seeded"

[[segments]]
index = 1
slot = 1
kind = "weights"
writable = false

[[segments]]
index = 2
slot = 2
kind = "ram"
writable = true
